# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 809267334b315738f67989c118d9f81917a1f875752b36a92dc9fe1aa293dc8dfbca2c2b56450daa3c306f486cfc62ddbab46f1f290b14ddc230021343471777

test:
  secret_key_base: 72dc06acbcd13eb5da1f4f57879e79a9bd80ed962e4b45e56eba15d843d3a9746488b03a47c7a8d3672668db83217f0c8f98efe9b431d3cd895d62f247bc9367

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
